### ISSUE TITLE
Не работает с версией PHP 8.2

### ISSUE THREAD

**Issue by AiratHalitov** [AiratHalitov/airat-aibolit-update#2]
Нужно исправить ошибки, т.к. скрипт ai-bolit не работает с версией php8.0
Если кто-то возьмется исправить - кидайте Pull Request.

**Comment by LeMaX10** [comment]
Скрипт айболита и его сигнатуры принадлежат cloudlinux т.к компания была куплена. Их использование запрещено в своих продуктах...

Григорий Земсков не раз об этом говорил. К сожалению айболит потерян... теперь все это принадлежит и используется в imunufy360

**Comment by rvalitov** [comment]
@AiratHalitov я так понимаю что скрипт уже работает с версией 8? И можно закрыть это обсуждение?

**Comment by AiratHalitov** [comment]
Я у себя ошибку получил во время сканирования на PHP 8.2 на этапе генерации отчета:

```
PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /home/airat/tmp/airat-aibolit-update/ai-bolit/ai-bolit-hoster.php:3740
Stack trace:
#0 /home/airat/tmp/airat-aibolit-update/ai-bolit/ai-bolit-hoster.php(1185): HTMLReport->generateReport()
#1 {main}
  thrown in /home/airat/tmp/airat-aibolit-update/ai-bolit/ai-bolit-hoster.php on line 3740
```

А еще до этого кучу предупреждений, вот весь лог: 

```
$ ./run-aibolit.sh
PHP Deprecated:  Creation of dynamic property FileFilter::$ignore_excludes is deprecated in /home/airat/tmp/airat-aibolit-update/ai-bolit/ai-bolit-hoster.php on line 5914
PHP Deprecated:  Creation of dynamic property FileFilter::$check_file_patterns is deprecated in /home/airat/tmp/airat-aibolit-update/ai-bolit/ai-bolit-hoster.php on line 5964
PHP Deprecated:  Creation of dynamic property FileFilter::$check_file_not_patterns is deprecated in /home/airat/tmp/airat-aibolit-update/ai-bolit/ai-bolit-hoster.php on line 5974
PHP Deprecated:  Creation of dynamic property FileFilter::$ignore_dots is deprecated in /home/airat/tmp/airat-aibolit-update/ai-bolit/ai-bolit-hoster.php on line 5992
PHP Deprecated:  Creation of dynamic property FileFilter::$imunify_filter is deprecated in /home/airat/tmp/airat-aibolit-update/ai-bolit/ai-bolit-hoster.php on line 6023
Malware signatures: 7285
PHP Fatal error:  Uncaught TypeError: implode(): Argument #1 ($pieces) must be of type array, string given in /home/airat/tmp/airat-aibolit-update/ai-bolit/ai-bolit-hoster.php:852
Stack trace:
#0 /home/airat/tmp/airat-aibolit-update/ai-bolit/ai-bolit-hoster.php(852): implode()
#1 {main}
  thrown in /home/airat/tmp/airat-aibolit-update/ai-bolit/ai-bolit-hoster.php on line 852
PHP Deprecated:  Creation of dynamic property FileFilter::$ignore_excludes is deprecated in /home/airat/tmp/airat-aibolit-update/ai-bolit/ai-bolit-hoster.php on line 5914
PHP Deprecated:  Creation of dynamic property FileFilter::$check_file_patterns is deprecated in /home/airat/tmp/airat-aibolit-update/ai-bolit/ai-bolit-hoster.php on line 5964
PHP Deprecated:  Creation of dynamic property FileFilter::$check_file_not_patterns is deprecated in /home/airat/tmp/airat-aibolit-update/ai-bolit/ai-bolit-hoster.php on line 5974
PHP Deprecated:  Creation of dynamic property FileFilter::$ignore_dots is deprecated in /home/airat/tmp/airat-aibolit-update/ai-bolit/ai-bolit-hoster.php on line 5992
PHP Deprecated:  Creation of dynamic property FileFilter::$imunify_filter is deprecated in /home/airat/tmp/airat-aibolit-update/ai-bolit/ai-bolit-hoster.php on line 6023
Malware signatures: 7285
PHP Deprecated:  Creation of dynamic property Scanner::$suspicious is deprecated in /home/airat/tmp/airat-aibolit-update/ai-bolit/ai-bolit-hoster.php on line 6353
Found 2026 files in 309 directories.
Start scanning '/home/airat/tmp/airat-aibolit-update/ai-bolit'.

100.0% [irat/tmp/airat-aibolit-update/ai-bolit/AIBOLIT-BINMALWARE.db] 2026 of 2026.  [Avg: 33 files/s] [Mlw:0|0]                                                
Building report [ mode = 2 ]

PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /home/airat/tmp/airat-aibolit-update/ai-bolit/ai-bolit-hoster.php:3740
Stack trace:
#0 /home/airat/tmp/airat-aibolit-update/ai-bolit/ai-bolit-hoster.php(1185): HTMLReport->generateReport()
#1 {main}
  thrown in /home/airat/tmp/airat-aibolit-update/ai-bolit/ai-bolit-hoster.php on line 3740
```

**Comment by rvalitov** [comment]
А понятно теперь что речь про 8.2. Потому что у меня на 8.0 запустилось без проблем. На 8.2 не проверял.

**Comment by AiratHalitov** [comment]
Исправил проблему: https://github.com/AiratHalitov/airat-aibolit-update/commit/62d57753ed416cd5f0ceb87b5544b2d552065db7
Может остальные ошибки тоже поправлю. 
Сейчас у меня заработал скрипт и отчет сгенерировался. Заменил `count(` на `count((array)`

**Comment by AiratHalitov** [comment]
Остались предупреждения `PHP Deprecated:  Creation of dynamic property ... is deprecated in `
в строках 
5914
5964
5974
5992
6023
6353
в файле [/ai-bolit/ai-bolit-hoster.php](https://github.com/AiratHalitov/airat-aibolit-update/blob/main/ai-bolit/ai-bolit-hoster.php)

**Comment by AiratHalitov** [comment]
Всё исправил https://github.com/AiratHalitov/airat-aibolit-update/commit/787781456527340d0b2c90a58c8e2ecd1daa0f94
Больше нет предупреждений
